---
title: "Data exploration"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: spacelab
    code_folding: hide
---

```{r setup}
library(tidyverse)
library(modelr)
library(dplyr)
require(dplyr)
library(lubridate)
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

```{r}
anxiety_df = read.csv("Indicators_of_Anxiety_or_Depression_Based_on_Reported_Frequency_of_Symptoms_During_Last_7_Days.csv") %>%  
  janitor::clean_names() %>% 
  select(indicator, group, subgroup, value) %>% 
  filter(indicator == "Symptoms of Anxiety Disorder or Depressive Disorder") %>% 
  filter(group == "By Age") %>% 
  group_by(subgroup) %>%
  mutate(row = row_number()) %>% 
  pivot_wider(
    names_from = group,
    values_from = value
  ) %>% 
  rename(value = 'By Age') %>% 
  select(-row, -indicator)

anxiety_df
```


```{r plot}
anxiety_df %>% 
  ggplot(aes(x = subgroup, y = value)) + 
  geom_boxplot() + 
  labs(
    title = "Symptoms of Anxiety or Depressive Disorder by Age Group",
    x = "Age group",
    y = "Frequency of anxiety or depressive symptoms"
  )
```

```{r}
race_df = read.csv("Indicators_of_Anxiety_or_Depression_Based_on_Reported_Frequency_of_Symptoms_During_Last_7_Days.csv") %>%  
  janitor::clean_names() %>% 
  select(indicator, group, subgroup, value) %>% 
  filter(indicator == "Symptoms of Anxiety Disorder or Depressive Disorder") %>% 
  filter(group == "By Race/Hispanic ethnicity") %>% 
  group_by(subgroup) %>%
  mutate(row = row_number()) %>% 
  pivot_wider(
    names_from = group,
    values_from = value
  ) %>% 
  rename(value = 'By Race/Hispanic ethnicity') %>% 
  select(-row, -indicator)

race_df
```

```{r plot2}
race_df %>% 
  ggplot(aes(x = subgroup, y = value)) + 
  geom_boxplot() + 
  labs(
    title = "Symptoms of Anxiety or Depressive Disorder by Race/ethnicity",
    x = "Race/ethnicity",
    y = "Frequency of anxiety or depressive symptoms"
  )
```

```{r}
sex_df = read.csv("Indicators_of_Anxiety_or_Depression_Based_on_Reported_Frequency_of_Symptoms_During_Last_7_Days.csv") %>%  
  janitor::clean_names() %>% 
  select(indicator, group, subgroup, value) %>% 
  filter(indicator == "Symptoms of Anxiety Disorder or Depressive Disorder") %>% 
  filter(group == "By Sex") %>% 
  group_by(subgroup) %>%
  mutate(row = row_number()) %>% 
  pivot_wider(
    names_from = group,
    values_from = value
  ) %>% 
  rename(value = 'By Sex') %>% 
  select(-row, -indicator)

sex_df
```

```{r plot3}
sex_df %>% 
  ggplot(aes(x = subgroup, y = value)) + 
  geom_boxplot() + 
  labs(
    title = "Symptoms of Anxiety or Depressive Disorder by Sex",
    x = "Sex",
    y = "Frequency of anxiety or depressive symptoms"
  )
```

```{r}
education_df = read.csv("Indicators_of_Anxiety_or_Depression_Based_on_Reported_Frequency_of_Symptoms_During_Last_7_Days.csv") %>%  
  janitor::clean_names() %>% 
  select(indicator, group, subgroup, value) %>% 
  filter(indicator == "Symptoms of Anxiety Disorder or Depressive Disorder") %>% 
  filter(group == "By Education") %>% 
  group_by(subgroup) %>%
  mutate(row = row_number()) %>% 
  pivot_wider(
    names_from = group,
    values_from = value
  ) %>% 
  rename(value = 'By Education') %>% 
  select(-row, -indicator)

education_df
```

```{r plot4}
education_df %>% 
  ggplot(aes(x = subgroup, y = value)) + 
  geom_boxplot() + 
  labs(
    title = "Symptoms of Anxiety or Depressive Disorder by Education",
    x = "Education level",
    y = "Frequency of anxiety or depressive symptoms"
  )
```