---
title: "Plotly and flexdashboard"
author: "Brandon Rojas"
date: "11/6/2021"
output: html_document
---

```{r}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(p8105.datasets)

library(plotly)
```

```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2) %>% 
  select(neighbourhood_group, neighbourhood, stars, price, room_type, lat, long) %>% 
  filter(
    neighbourhood_group == "Manhattan",
    room_type == "Entire home/apt",
    price %in% 100:500
  ) %>% 
  drop_na(stars)
```

Scatterplot

```{r}
nyc_airbnb %>% 
  mutate(text_label = str_c("Price: $", price, "\nStars:", stars)) %>%
  plot_ly(
    x = ~lat, y = ~long, type = "scatter", modde = "markers",         #~ means total
    color = ~price, text = ~text_label, alpha = 0.5
  )
```


## Plotly boxplot

```{r}
nyc_airbnb %>% 
  mutate(
    neighbourhood = fct_reorder(neighbourhood, price)
  ) %>%
  plot_ly(y = ~price, color = 
            ~neighbourhood, type = "box")

```

## Bar Chart


```{r}
nyc_airbnb %>% 
  count(neighbourhood) %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>% 
  plot_ly(x = ~neighbourhood, y = ~n, color = ~neighbourhood, type = "bar", colors = "viridis")
```

For making plots quickly, use ggplotly. Just use plotly stuff in using ggplot.
```{r}
gg_lat_long = 
  nyc_airbnb %>% 
  ggplot(aes(x = lat, y = long, color = price)) + 
  geom_point()

ggplotly(gg_lat_long)
```

